### ISSUE TITLE
3.x Install location

### ISSUE THREAD

**Issue by davidyell** [burzum/cakephp-imagine-plugin#32]
I was just looking through the documentation and I noticed that you suggest putting the plugin into `app/Vendor` but, in 3.x the folder would be `src/vendor` and also, the plugin structure has changed so that plugins are just loaded from the composer folder.

**Comment by burzum** [comment]
Thank's, I'm aware of that, just didn't realize I haven't updated this. :(

I've seen you've started an upload plugin that uses imagine as well.

**Comment by davidyell** [comment]
That will be great, as I've copied and pasted my transformation code from some tutorials due to Imagines documentation being a bit thin.

**Comment by burzum** [comment]
Yes, it's documentation could be a little better. Creating a wrapper around it's API made it a lot more convenient to use it, at least for me.

**Comment by davidyell** [comment]
Thanks for the prompt response @burzum, appreciated!
