### ISSUE TITLE
Cakephp 3.6 compatibility

### ISSUE THREAD

**Issue by stripthis** [burzum/cakephp-imagine-plugin#46]
Hello,

Do you have any plans on upgrading this plugin to work with Cakephp 3.6?
Thanks!

**Comment by burzum** [comment]
@stripthis https://github.com/burzum/cakephp-imagine-plugin/tree/3.x should be 3.6 compatible. But what, except the deprecation warnings, is stopping you from using it with an older version?

**Comment by stripthis** [comment]
@burzum yes I was talking about the deprecation warnings, as far as I know it was working fine otherwise. :)

**Comment by burzum** [comment]
@stripthis give this branch a try. https://github.com/burzum/cakephp-imagine-plugin/tree/3.x
